### ISSUE TITLE
Not getting razorpay_signature  on success callback

### ISSUE THREAD

**Issue by chinthu** [razorpay/razorpay-cordova#117] opened 2020-01-13 13:29 UTC
* **Common to Both platforms :-**

  - [ ] I have gone through the README(https://github.com/razorpay/razorpay-cordova)
  - [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-cordova/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-cordova/releases)
  - [ ] I have cleaned my project.

* **Specific to iOS Users :-**
  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/razorpay-cordova)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

**Comment by ganeshrvel** [comment] 2020-05-19 21:50
If anyone else is wondering why these values are missing in the response, just pass the `order_id` in the options object.

Something like this:

```html
<html>
  <script src="https://checkout.razorpay.com/v1/checkout.js" />
  <script>
    function razorpay() {
      const options = {
        key: "our_key",
        amount: 100,
        name: "<App name>",
        description: "Desc",
        currency: this.currency,
        order_id: 'order_dfddds68478383', //<------- add this line

        handler: async (response) => {
          const orderId = response.razorpay_order_id;
          const paymentId = response.razorpay_payment_id;
          const signature = response.razorpay_signature;
        },

        prefill: {
          name: "name",
          email: "email",
          contact: "contact",
        },
      };

      const razorpay = new window.Razorpay(options);

      razorpay.open();
    }
  </script>
</html>
```

**Comment by mail2bapi** [comment] 2020-10-13 19:36
As @ganeshrvel  said, "order_id" is the culprit here.

**Comment by vivekshindhe** [comment] 2020-10-14 08:20
Hope the issue is resolved. Closing it. Please create another ticket if you need support.

**Closed by vivekshindhe** 2020-10-14 08:20 UTC

**Comment by ganeshrvel** [comment] 2020-10-14 16:51
@vivekshindhe care to mention this about the mandatory `order_id` in your document?

**Comment by vivekshindhe** [comment] 2020-10-14 17:07
There isn't a payload that doesn't have order_id in the document. But thanks for the mention. Will look into it.
